### ISSUE TITLE
What does the module do?

### ISSUE THREAD

**Issue by benkasminbullock** [michal-josef-spacek/CSS-Struct#2]
It's not very clear what the module does, because there's no synopsis or description. Perhaps it would be useful to include a working example in the synopsis section of the module and a description of what it does?

**Comment by michal-josef-spacek** [comment]
@benkasminbullock Hi. Ha, I am looking, that, there are not examples. Sorry for it, I will fix it.

**Comment by michal-josef-spacek** [comment]
So, i added some doc, examples. And release modules.

If you are interested, the best way is run this:
`cpanm App::Pod::Example CSS::Struct CSS::Struct::Output::Indent`

`pod-example -r CSS::Struct::Output::Raw`
`pod-example -p CSS::Struct::Output::Raw`

`pod-example -r CSS::Struct::Output::Indent`
`pod-example -p CSS::Struct::Output::Indent`

`pod-example -r CSS::Struct 0`
`pod-example -r CSS::Struct 1`
`pod-example -p CSS::Struct`

**Comment by benkasminbullock** [comment]
I am getting errors from metacpan at the moment:

https://metacpan.org/source/SKIM/CSS-Struct-0.04

just gives "not found".

Perhaps it is transient.

Thanks for helping me.

**Comment by michal-josef-spacek** [comment]
@benkasminbullock  I believe, that is transient ;-)

**Comment by benkasminbullock** [comment]
Yes, it appears now. Thank you for doing this work!

**Comment by michal-josef-spacek** [comment]
@benkasminbullock Thanks. FYI: https://metacpan.org/pod/CSS::Struct::Output::Indent::ANSIColor (in progress still)
